-- File generated by the BNF Converter (bnfc 2.9.5).
{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}

module ErrM where

import Prelude (Either(..), String, (<>), const, id)

import Control.Applicative (Alternative(..))
import Control.Monad (MonadFail(..), MonadPlus(..))

-- | Error monad with 'String' error messages.
type Err = Either String

instance MonadFail Err where
  fail = Left

instance Alternative Err where
  empty = Left "Err.empty"
  (<|>) Left {} = id
  (<|>) x@Right {} = const x

instance MonadPlus Err where
  mzero = empty
  mplus = (<|>)

(<+>) :: Err [a] -> Err [a] -> Err [a]
(<+>) (Left s) _ = Left s
(<+>) _ (Left s) = Left s
(<+>) (Right m1) (Right m2) = Right (m1 <> m2)
