name: Haskell CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.8.2'
        cabal-version: '3.8'

    - name: Install dependencies
      run: |
        cabal update
        cabal v1-install alex-3.5.1.0 happy-1.20.1.1 
        cabal v1-install BNFC-2.9.5
        cabal v1-install --only-dependencies --enable-benchmarks --enable-tests
    - name: Build
      run: make build
    - name: Run tests
      run: make test
